### Listar todas las tareas
GET http://localhost:3000/todos?completed=0&fecha=2025-10-10

### Listar una tarea por id
GET http://localhost:3000/todos/80a996dc-b520-11f0-8c5c-2ea2e8af62fb

### Crear una tarea
POST http://localhost:3000/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMwZGI3NTAxLWI0NTYtMTFmMC04ZjgzLTJlYTJlOGFmNjJmYiIsIm5hbWUiOiJKdWFuIEFsdmFyZW5nYSIsImlhdCI6MTc2MjgxODUwMywiZXhwIjoxNzk0Mzc2MTAzfQ.fQ0-X7afDRYCszHsDBQWikfEPVbsqE6KEOgpJaJZZr8

{
    "title":"Tercera tarea creada",
    "description":"Creada con named params",
    "completed": false
}

### Actualizar una tarea
PUT http://localhost:3000/todos/10
Content-Type: application/json

{
    "title":"Modificacion",
    "description": "Pendiente de desplegar a prod",
    "completed": false
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"jealvarengar@unah.edu.hn",
    "password": "abc1234**"
}


### Cambio de contraseña
PUT http://localhost:3000/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMwZGI3NTAxLWI0NTYtMTFmMC04ZjgzLTJlYTJlOGFmNjJmYiIsImlhdCI6MTc2Mjk5MDgyMiwiZXhwIjoxNzYyOTkxNDIyfQ.AZiiu-spgFhZAna-5uDGnVof95pUqCCXHOv6j75nmb8

{
    "password":"abc1234**",
    "confirm_password": "abc1234**"
}

### Recuperar contraseña
POST http://localhost:3000/auth/recover-password
Content-Type: application/json

{
    "email": "jealvarengar@unah.edu.hn"
}
